# Generated by Django 4.2.5 on 2023-10-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('post', 'Статья'), ('news', 'Новость')], max_length=7),
        ),
    ]
